/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Directors: () => import('#controllers/directors_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Students: () => import('#controllers/students_controller'),
  Teachers: () => import('#controllers/teachers_controller'),
}
